/**
 * Smooth Scroll v4.7.0 - minified
 * Animate scrolling to anchor links, by Chris Ferdinandi.
 * http://gomakethings.com
 *
 * Additional contributors:
 * https://github.com/cferdinandi/smooth-scroll#contributors
 *
 * Free to use under the MIT License.
 * http://gomakethings.com/mit/
 */
(function(e,t){if(typeof define==="function"&&define.amd){define(t)}else if(typeof exports==="object"){module.exports=t}else{e.smoothScroll=t(e)}})(this,function(e){"use strict";var t={};var n=!!document.querySelector&&!!e.addEventListener;var r={speed:500,easing:"easeInOutCubic",offset:0,updateURL:false,callbackBefore:function(){},callbackAfter:function(){}};var i=function(e,t){for(var n in t){if(Object.prototype.hasOwnProperty.call(t,n)){e[n]=t[n]}}return e};var s=function(e,t,n){if(Object.prototype.toString.call(e)==="[object Object]"){for(var r in e){if(Object.prototype.hasOwnProperty.call(e,r)){t.call(n,e[r],r,e)}}}else{for(var i=0,s=e.length;i<s;i++){t.call(n,e[i],i,e)}}};var o=function(e,t){var n;if(e==="easeInQuad")n=t*t;if(e==="easeOutQuad")n=t*(2-t);if(e==="easeInOutQuad")n=t<.5?2*t*t:-1+(4-2*t)*t;if(e==="easeInCubic")n=t*t*t;if(e==="easeOutCubic")n=--t*t*t+1;if(e==="easeInOutCubic")n=t<.5?4*t*t*t:(t-1)*(2*t-2)*(2*t-2)+1;if(e==="easeInQuart")n=t*t*t*t;if(e==="easeOutQuart")n=1- --t*t*t*t;if(e==="easeInOutQuart")n=t<.5?8*t*t*t*t:1-8*--t*t*t*t;if(e==="easeInQuint")n=t*t*t*t*t;if(e==="easeOutQuint")n=1+ --t*t*t*t*t;if(e==="easeInOutQuint")n=t<.5?16*t*t*t*t*t:1+16*--t*t*t*t*t;return n||t};var u=function(e,t,n){var r=0;if(e.offsetParent){do{r+=e.offsetTop;e=e.offsetParent}while(e)}r=r-t-n;return r>=0?r:0};var a=function(){return Math.max(document.body.scrollHeight,document.documentElement.scrollHeight,document.body.offsetHeight,document.documentElement.offsetHeight,document.body.clientHeight,document.documentElement.clientHeight)};var f=function(e){return e.replace(/^\s+|\s+$/g,"")};var l=function(e){var t={};if(e){e=e.split(";");e.forEach(function(e){e=f(e);if(e!==""){e=e.split(":");t[e[0]]=f(e[1])}})}return t};var c=function(e,t){if(history.pushState&&(t||t==="true")){history.pushState({pos:e.id},"",e)}};t.animateScroll=function(t,n,s,f){var h=i(r,s||{});var p=l(t?t.getAttribute("data-options"):null);h=i(h,p);var d=document.querySelector("[data-scroll-header]");var v=d===null?0:d.offsetHeight+d.offsetTop;var m=e.pageYOffset;var g=u(document.querySelector(n),v,parseInt(h.offset,10));var y;var b=g-m;var w=a();var E=0;var S,x;if(t&&t.tagName.toLowerCase()==="a"&&f){f.preventDefault()}c(n,h.updateURL);var T=function(r,i,s){var o=e.pageYOffset;if(r==i||o==i||e.innerHeight+o>=w){clearInterval(s);h.callbackAfter(t,n)}};var N=function(){E+=16;S=E/parseInt(h.speed,10);S=S>1?1:S;x=m+b*o(h.easing,S);e.scrollTo(0,Math.floor(x));T(x,g,y)};var C=function(){h.callbackBefore(t,n);y=setInterval(N,16)};if(e.pageYOffset===0){e.scrollTo(0,0)}C()};t.init=function(e){if(!n)return;var o=i(r,e||{});var u=document.querySelectorAll("[data-scroll]");s(u,function(e){e.addEventListener("click",t.animateScroll.bind(null,e,e.getAttribute("href"),o),false)})};return t})